---
title: "results reproduction"
output: html_document
author: "Jocelyn Hu"
---
```{r}
library(tidyverse)
library(yardstick)
library(ggplot2)
library(mosaic)
library(stargazer)
require(Stat2Data)
library(scales)
library(readr)
library(rms)
```

```{r}
library(haven)
Dyadic_dta<- read_dta("Data/AttanasioEtAl2011Dyadic.dta")
Dyadic<-read.csv("Dyadic.csv")
Dyadic_mdum<-read.csv("Dyadic_mdum.csv")
```

```{r, eval = FALSE}
glimpse(Dyadic_dta$inreg)
```

```{r, eval = FALSE}
str(Dyadic)
```

Mutate var stranger which does no exist in the original dataframe 
```{r}
tally(~Dyadic$municode)
tally(~Dyadic$samegroup)
#Dyadic<-na.omit(Dyadic) 
Dyadic<-Dyadic%>%
  mutate(stranger = 1 - as.numeric(Dyadic$frfam))

```


```{r}
pervar<-c("samegroup","friend2","friendfamily","stranger", "frfam","family2", "friend1", "family1", "frfamcl", "difurban", "diffemale","difmarried")
for (i in pervar) {
star[[i]] <- (as.numeric(Dyadic[[i]]))*100
}
# 
# Dyadic[["sumtcons"]] <- (as.numeric(Dyadic[["sumtcons"]]))/1000
# 
# Dyadic[["diftcons"]] <- (as.numeric(Dyadic[["diftcons"]]))/1000
```

https://www.princeton.edu/~otorres/NiceOutputR.pdf

The variable difmar's name should be 'difmarried' and nummar should be nummarried.


```{r}
stargazer(subset(star[c("samegroup","difchoice1","sumchoice1","frfam","friend2","friendfamily", "family2", "friend1", "family1","stranger","frfamcl", "difurban", "diffemale", "difyage", "difysch", "difmarried","diftcons","difcons", "difhhsize","difwin1","sumurban","sumfemale","sumyage", "sumysch", "nummarried", "sumtcons", "sumcons", "sumhhsize", "sumwin1")],star$inreg ==1), type = "html", title="Table4: Dyadic Variables", digits=4, out="table4.html", covariate.labels = c("Joined same group in round 2(%)", "Difference in gamble choice(round1)","Sum of gamble choices (round 1)", "Friends and family: One or both recognized friendship or kinship(%)","Both recognized friendship(%)","Both recognized kinship(%)","One recognized friendship, other kinship(%)","One recognized friendship(%)", "One recognized kinship(%)", "Stranger(%)","Geographically proximate friends and family(%)","One lives in the municipal centre, one not(%)","Different genders(%)","Difference in age(years)","Difference in education (years)","Difference in marital status(%)","Difference in household consumption ('000s Pesos/month)","Difference in log household consumption per month","Difference in household size","Difference in round 1 winnings ('000 Pesos)","Number who live in the municipal centre","Number of females","Sum of ages (years)","Sum of education (years)","Number married","Sum of household consumption ('000s Pesos/month)","Sum of log household consumption per month","Sum of household sizes","Sum of round 1 winnings ('000s Pesos)"), summary.stat = c("mean", "sd"))

```




```{r}
library(dplyr)
Dyadic1 <- Dyadic %>%
  subset(inreg == 1)%>%
  mutate(Observations = 0)%>%
  select(c("samegroup","difchoice1","sumchoice1","frfam","friend2","friendfamily", "family2", "friend1", "family1","stranger","frfamcl", "difurban", "diffemale", "difyage", "difysch", "difmarried","diftcons","difcons", "difhhsize","difwin1","sumurban","sumfemale","sumyage", "sumysch", "nummarried", "sumtcons", "sumcons", "sumhhsize", "sumwin1","Observations"))


Dyadic2 <- Dyadic %>%
  subset(inreg == 1 & frfamcl== 1)%>%
  mutate(Observations = 0)%>%
  select(c("samegroup","difchoice1","sumchoice1","frfam","friend2","friendfamily", "family2", "friend1", "family1","stranger","frfamcl", "difurban", "diffemale", "difyage", "difysch", "difmarried","diftcons","difcons", "difhhsize","difwin1","sumurban","sumfemale","sumyage", "sumysch", "nummarried", "sumtcons", "sumcons", "sumhhsize", "sumwin1","Observations"))

Dyadic3 <- Dyadic %>%
  subset(inreg == 1 & frfamcl== 0)%>%
  mutate(Observations = 0)%>%
  select(c("samegroup","difchoice1","sumchoice1","frfam","friend2","friendfamily", "family2", "friend1", "family1","stranger","frfamcl", "difurban", "diffemale", "difyage", "difysch", "difmarried","diftcons","difcons", "difhhsize","difwin1","sumurban","sumfemale","sumyage", "sumysch", "nummarried", "sumtcons", "sumcons", "sumhhsize", "sumwin1","Observations"))
```




```{r}
pervar<-c("samegroup","friend2","friendfamily","stranger", "frfam","family2", "friend1", "family1", "difurban","frfamcl", "diffemale","difmarried")

for (i in pervar) {
Dyadic1[[i]] <- (as.numeric(Dyadic1[[i]]))*100
}


pervar<-c("samegroup","friend2","friendfamily","stranger", "frfam","family2", "friend1", "family1", "difurban","frfamcl", "diffemale","difmarried")

for (i in pervar) {
Dyadic2[[i]] <- (as.numeric(Dyadic2[[i]]))*100
}

pervar<-c("samegroup","friend2","friendfamily","stranger", "frfam","family2", "friend1", "family1", "difurban","frfamcl", "diffemale","difmarried")

for (i in pervar) {
Dyadic3[[i]] <- (as.numeric(Dyadic3[[i]]))*100
}

```

```{r}
library(fBasics)
sum1<-basicStats(Dyadic1)[c("Mean", "Stdev"),]
sum1<-data.frame(t(sum1))
sum2<-basicStats(Dyadic2)[c("Mean"),]
sum2<-data.frame(t(sum2))
sum3<-basicStats(Dyadic3)[c("Mean"),]
sum3<-data.frame(t(sum3))

```

```{r}
table4<-cbind(sum1,sum2,sum3)
table4[17,1]<-(table4[17,1])/1000
table4[17,2]<-(table4[17,2])/1000
table4[17,3]<-table4[17,3]/1000
table4[17,4]<-table4[17,4]/1000 
table4[26,1]<-table4[26,1]/1000 
table4[26,2]<-table4[26,2]/1000
table4[26,3]<-table4[26,3]/1000
table4[26,4]<-table4[26,4]/1000

is.num <- sapply(table4, is.numeric)
table4[is.num] <- lapply(table4[is.num], round, 3)
```

```{r}
#table4<-as.data.frame(lapply(table4, na.omit))
# table4<-transform(table4, Mean = as.numeric(Mean))
# table4<-transform(table4, Mean = as.numeric(Mean), Mean.1 = as.numeric(Mean.1), Mean.2 = as.numeric(Mean.2))
```

```{r}
table4[1,1]<-paste(table4[1,1],"%",sep = "")
table4[1,3]<-paste(table4[1,3],"%",sep = "")
table4[1,4]<-paste(table4[1,4],"%",sep = "")
```

```{r}
table4[4:13,1]<-paste(table4[4:13,1],"%",sep = "")
table4[4:13,3]<-paste(table4[4:13,3],"%",sep = "")
table4[4:13,4]<-paste(table4[4:13,4],"%",sep = "")
table4[16,1]<-paste(table4[16,1],"%",sep = "")
table4[16,3]<-paste(table4[16,3],"%",sep = "")
table4[16,4]<-paste(table4[16,4],"%",sep = "")
table4[1,2]<-" "
table4[4:13,2]<-" "
table4[16,2]<-" "

```

```{r}
table4[30,]<-c("86518"," ","4466","82052")

is.num <- sapply(table4, is.numeric)
table4[is.num] <- lapply(table4[is.num], round, 3)
```


```{r, result = 'asis'}
#position = "float_right" 
library(kableExtra)
library(params)
library(knitr)
knitr::kable(table4,format = "html",row.names = NA, col.names = c("Mean/Prop","s.d.","Mean/Prop","s.d."), align = 'l',escape = F,booktabs = F)%>%
 add_header_above(c(" " = 1, "All dyads" = 2,"Close family and friends" = 1, "Other dyads" =1))%>%  kable_styling(bootstrap_options = c("striped"), full_width = F, font_size = 16)%>%column_spec(1,border_right = T)%>%column_spec(2,italic = T)%>%add_header_above(c("Table4: Experimental data"=5))
```




